# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segreteria_dialog_inserisci_laurea_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_segreteria_dialog_inserisci_laurea(object):
    def setupUi(self, segreteria_dialog_inserisci_laurea):
        segreteria_dialog_inserisci_laurea.setObjectName("segreteria_dialog_inserisci_laurea")
        segreteria_dialog_inserisci_laurea.resize(394, 379)
        self.gridLayout = QtWidgets.QGridLayout(segreteria_dialog_inserisci_laurea)
        self.gridLayout.setObjectName("gridLayout")
        self.InsertLaureaButton = QtWidgets.QPushButton(segreteria_dialog_inserisci_laurea)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InsertLaureaButton.setFont(font)
        self.InsertLaureaButton.setObjectName("InsertLaureaButton")
        self.gridLayout.addWidget(self.InsertLaureaButton, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(segreteria_dialog_inserisci_laurea)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MtrLaurea = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.MtrLaurea.setFont(font)
        self.MtrLaurea.setText("")
        self.MtrLaurea.setObjectName("MtrLaurea")
        self.verticalLayout_2.addWidget(self.MtrLaurea)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(segreteria_dialog_inserisci_laurea)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NomeLaurea = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NomeLaurea.setFont(font)
        self.NomeLaurea.setText("")
        self.NomeLaurea.setObjectName("NomeLaurea")
        self.verticalLayout_4.addWidget(self.NomeLaurea)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)

        self.retranslateUi(segreteria_dialog_inserisci_laurea)
        QtCore.QMetaObject.connectSlotsByName(segreteria_dialog_inserisci_laurea)

    def retranslateUi(self, segreteria_dialog_inserisci_laurea):
        _translate = QtCore.QCoreApplication.translate
        segreteria_dialog_inserisci_laurea.setWindowTitle(_translate("segreteria_dialog_inserisci_laurea", "UniWorld - Segreteria Inserisci Laurea"))
        self.InsertLaureaButton.setText(_translate("segreteria_dialog_inserisci_laurea", "Inserisci Laurea"))
        self.groupBox_2.setTitle(_translate("segreteria_dialog_inserisci_laurea", "Matricola Laurea"))
        self.groupBox_4.setTitle(_translate("segreteria_dialog_inserisci_laurea", "Nome Laurea"))
