# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segreteria_dialog_inserisci_appello_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_segreteria_dialog_inserisci_appello(object):
    def setupUi(self, segreteria_dialog_inserisci_appello):
        segreteria_dialog_inserisci_appello.setObjectName("segreteria_dialog_inserisci_appello")
        segreteria_dialog_inserisci_appello.resize(394, 476)
        self.gridLayout = QtWidgets.QGridLayout(segreteria_dialog_inserisci_appello)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(segreteria_dialog_inserisci_appello)
        self.groupBox_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBoxCorsi = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxCorsi.setObjectName("comboBoxCorsi")
        self.verticalLayout_3.addWidget(self.comboBoxCorsi)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.InsertAppelloButton = QtWidgets.QPushButton(segreteria_dialog_inserisci_appello)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InsertAppelloButton.setFont(font)
        self.InsertAppelloButton.setObjectName("InsertAppelloButton")
        self.gridLayout.addWidget(self.InsertAppelloButton, 6, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(segreteria_dialog_inserisci_appello)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(segreteria_dialog_inserisci_appello)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.Luogo = QtWidgets.QTextEdit(self.groupBox_2)
        self.Luogo.setGeometry(QtCore.QRect(10, 30, 351, 31))
        self.Luogo.setObjectName("Luogo")
        self.gridLayout.addWidget(self.groupBox_2, 4, 0, 1, 1)

        self.retranslateUi(segreteria_dialog_inserisci_appello)
        QtCore.QMetaObject.connectSlotsByName(segreteria_dialog_inserisci_appello)

    def retranslateUi(self, segreteria_dialog_inserisci_appello):
        _translate = QtCore.QCoreApplication.translate
        segreteria_dialog_inserisci_appello.setWindowTitle(_translate("segreteria_dialog_inserisci_appello", "UniWorld - Segreteria Inserisci Appello"))
        self.groupBox_3.setTitle(_translate("segreteria_dialog_inserisci_appello", "Corso"))
        self.InsertAppelloButton.setText(_translate("segreteria_dialog_inserisci_appello", "Inserisci Appello"))
        self.groupBox.setTitle(_translate("segreteria_dialog_inserisci_appello", "Data Appello"))
        self.groupBox_2.setTitle(_translate("segreteria_dialog_inserisci_appello", "Luogo"))
