# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segreteria_dialog_fornisci_date.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FornisciDate(object):
    def setupUi(self, FornisciDate):
        FornisciDate.setObjectName("FornisciDate")
        FornisciDate.resize(429, 503)
        self.verticalLayout = QtWidgets.QVBoxLayout(FornisciDate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(FornisciDate)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("text-align:center")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.AggiornaButton = QtWidgets.QPushButton(FornisciDate)
        self.AggiornaButton.setObjectName("AggiornaButton")
        self.horizontalLayout.addWidget(self.AggiornaButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(FornisciDate)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 401))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.TableView = QtWidgets.QVBoxLayout()
        self.TableView.setObjectName("TableView")
        self.verticalLayout_2.addLayout(self.TableView)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(FornisciDate)
        QtCore.QMetaObject.connectSlotsByName(FornisciDate)

    def retranslateUi(self, FornisciDate):
        _translate = QtCore.QCoreApplication.translate
        FornisciDate.setWindowTitle(_translate("FornisciDate", "UniWorld - Segreteria Inoltra Prenotazione"))
        self.label_4.setText(_translate("FornisciDate", "Richieste date "))
        self.AggiornaButton.setText(_translate("FornisciDate", "Aggiorna"))
        self.label_3.setText(_translate("FornisciDate", "Matricola"))
        self.label_2.setText(_translate("FornisciDate", "Esame"))
        self.label_5.setText(_translate("FornisciDate", "Nome"))
        self.label_6.setText(_translate("FornisciDate", "Cognome"))
        self.label_7.setText(_translate("FornisciDate", "Azione"))
